platform :ios, '14.0'

target 'TonWallet' do
  use_frameworks!

  pod 'SnapKit'
  pod 'R.swift'
  pod 'IGListKit'
  pod 'Atributika'
  pod 'Alamofire'
  pod 'Moya'
  pod 'Kingfisher'
  pod 'TweetNacl'
  pod 'BigInt'
  pod 'Starscream'
  pod 'PinLayout'
  
end
